export enum UserRole {
  POSTER = 'POSTER',
  TASKER = 'TASKER',
  BOTH = 'BOTH',
  ADMIN = 'ADMIN',
}

export enum KycLevel {
  NONE = 'NONE',
  BASIC = 'BASIC',
  ID_VERIFIED = 'ID_VERIFIED',
  PAYOUT = 'PAYOUT',
}

export enum TaskStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_REVIEW = 'PENDING_REVIEW',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum BidStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum EscrowStatus {
  HOLDING = 'HOLDING',
  RELEASED = 'RELEASED',
  REFUNDED = 'REFUNDED',
  DISPUTED = 'DISPUTED',
}

export enum TransactionType {
  CHARGE = 'CHARGE',
  TASKER_PAYOUT = 'TASKER_PAYOUT',
  PLATFORM_FEE = 'PLATFORM_FEE',
  REFUND = 'REFUND',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum DisputeResolution {
  TASKER_WINS = 'TASKER_WINS',
  POSTER_WINS = 'POSTER_WINS',
}

export enum DisputeReason {
  INCOMPLETE = 'INCOMPLETE',
  POOR_QUALITY = 'POOR_QUALITY',
  NO_SHOW = 'NO_SHOW',
  FRAUD = 'FRAUD',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
}

export enum MessageSenderType {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
}

export enum NotificationType {
  TASK_BID_RECEIVED = 'TASK_BID_RECEIVED',
  TASK_BID_ACCEPTED = 'TASK_BID_ACCEPTED',
  TASK_BID_REJECTED = 'TASK_BID_REJECTED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_STARTED = 'TASK_STARTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_CONFIRMED = 'TASK_CONFIRMED',
  TASK_CANCELLED = 'TASK_CANCELLED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYOUT_SENT = 'PAYOUT_SENT',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
}
